@startuml Архитектура_АгроТех_Системы_v4

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' === Участники ===
Person(operator, "Дежурный сотрудник", "Мониторинг данных")

System_Boundary(платформа, "АгроПром Х - Цифровая платформа мониторинга скота") {

Container(API, "API for Web or Mobile App")

Container_Boundary(server_agent, "АгроПром Х - Цифровая платформа (Сервис-агенты)") {
        Container(видеомониторинг, "Видеомониторинг скота", Данные с ферм)
        Container(датчики, "Датчики оборудования на фермах", "Кормушки, поилки, системы фильтрации воды и др")
        Container(уведомления, "Уведомление персонала на местах")
        Container(iot_платформа, "IoT платформа", Данные с ферм)
        Container(scada, "SCADA система", "Ignition", "Управление оборудованием на фермах")
}

Container_Boundary(central_server, "АгроПром Х - Цифровая платформа (Центральный сервер)") {

        Container(ИИ_сервис, "ИИ сервис", LLM Модель для анализа видеозаписей с ферм)
        Container(kafka, "Брокер сообщений", "Apache Kafka", "Шина данных")
        ContainerDb(данные,"Хранилища данных", Data Lake и DWH)
        Container(аналитика, "Аналитический модуль", "Python+Spark", "Анализ эффективности")
}

 Rel(видеомониторинг,iot_платформа, Передача данных)

 Rel(iot_платформа,ИИ_сервис, Передача данных)

 Rel(kafka,данные, Записывает данные)

 Rel(scada,kafka, "Публикует данные об уровне запаса еды")

 Rel(данные,аналитика, Передача данных)

 Rel(аналитика,API, Передача данных)

 Rel(датчики,scada, Передача сигналов по сети Интернет)

 Rel(operator,уведомления, "Мониторинг данных")

 Rel(ИИ_сервис,уведомления, Отправляет алерты по сети Интернет)
 Rel(ИИ_сервис,kafka, отправка событий)

 }

@enduml